services:
    ms-notification:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: ms-notification/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
            - '${VITE_PORT:-5173}:5173'
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - ms-notification
        depends_on:
            - ms-notification-mysql
    ms-notification-mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'ms-notification-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - ms-notification
    ms-notification-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: ms-notification-mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${SAIL_PHP_MY_ADMIN_PORT:-8080}:80'
        depends_on:
            - ms-notification-mysql
        networks:
            - ms-notification
networks:
    ms-notification:
        driver: bridge
volumes:
    ms-notification-mysql:
        driver: local
